// spot@public.bookTicker.v3.api.pb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.3
// source: PublicBookTickerV3Api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicBookTickerV3Api struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidPrice      string                 `protobuf:"bytes,1,opt,name=bidPrice,proto3" json:"bidPrice,omitempty"`
	BidQuantity   string                 `protobuf:"bytes,2,opt,name=bidQuantity,proto3" json:"bidQuantity,omitempty"`
	AskPrice      string                 `protobuf:"bytes,3,opt,name=askPrice,proto3" json:"askPrice,omitempty"`
	AskQuantity   string                 `protobuf:"bytes,4,opt,name=askQuantity,proto3" json:"askQuantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicBookTickerV3Api) Reset() {
	*x = PublicBookTickerV3Api{}
	mi := &file_PublicBookTickerV3Api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicBookTickerV3Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicBookTickerV3Api) ProtoMessage() {}

func (x *PublicBookTickerV3Api) ProtoReflect() protoreflect.Message {
	mi := &file_PublicBookTickerV3Api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicBookTickerV3Api.ProtoReflect.Descriptor instead.
func (*PublicBookTickerV3Api) Descriptor() ([]byte, []int) {
	return file_PublicBookTickerV3Api_proto_rawDescGZIP(), []int{0}
}

func (x *PublicBookTickerV3Api) GetBidPrice() string {
	if x != nil {
		return x.BidPrice
	}
	return ""
}

func (x *PublicBookTickerV3Api) GetBidQuantity() string {
	if x != nil {
		return x.BidQuantity
	}
	return ""
}

func (x *PublicBookTickerV3Api) GetAskPrice() string {
	if x != nil {
		return x.AskPrice
	}
	return ""
}

func (x *PublicBookTickerV3Api) GetAskQuantity() string {
	if x != nil {
		return x.AskQuantity
	}
	return ""
}

var File_PublicBookTickerV3Api_proto protoreflect.FileDescriptor

var file_PublicBookTickerV3Api_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x56, 0x33, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01,
	0x0a, 0x15, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x56, 0x33, 0x41, 0x70, 0x69, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69, 0x64, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x69, 0x64, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x62, 0x69, 0x64, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x69, 0x64, 0x51, 0x75, 0x61,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x42, 0x81, 0x01, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x78, 0x63, 0x2e,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x42, 0x1a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x6f, 0x6f, 0x6b,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x56, 0x33, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x48, 0x01, 0x50, 0x01, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x65, 0x78, 0x63, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x2f, 0x6d, 0x65, 0x78,
	0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x2f, 0x77, 0x65, 0x62, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_PublicBookTickerV3Api_proto_rawDescOnce sync.Once
	file_PublicBookTickerV3Api_proto_rawDescData []byte
)

func file_PublicBookTickerV3Api_proto_rawDescGZIP() []byte {
	file_PublicBookTickerV3Api_proto_rawDescOnce.Do(func() {
		file_PublicBookTickerV3Api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PublicBookTickerV3Api_proto_rawDesc), len(file_PublicBookTickerV3Api_proto_rawDesc)))
	})
	return file_PublicBookTickerV3Api_proto_rawDescData
}

var file_PublicBookTickerV3Api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PublicBookTickerV3Api_proto_goTypes = []any{
	(*PublicBookTickerV3Api)(nil), // 0: PublicBookTickerV3Api
}
var file_PublicBookTickerV3Api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PublicBookTickerV3Api_proto_init() }
func file_PublicBookTickerV3Api_proto_init() {
	if File_PublicBookTickerV3Api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PublicBookTickerV3Api_proto_rawDesc), len(file_PublicBookTickerV3Api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PublicBookTickerV3Api_proto_goTypes,
		DependencyIndexes: file_PublicBookTickerV3Api_proto_depIdxs,
		MessageInfos:      file_PublicBookTickerV3Api_proto_msgTypes,
	}.Build()
	File_PublicBookTickerV3Api_proto = out.File
	file_PublicBookTickerV3Api_proto_goTypes = nil
	file_PublicBookTickerV3Api_proto_depIdxs = nil
}
