// spot@public.increase.depth.v3.api.pb

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.3
// source: PublicIncreaseDepthsV3Api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicIncreaseDepthsV3Api struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Asks          []*PublicIncreaseDepthV3ApiItem `protobuf:"bytes,1,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids          []*PublicIncreaseDepthV3ApiItem `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	EventType     string                          `protobuf:"bytes,3,opt,name=eventType,proto3" json:"eventType,omitempty"`
	Version       string                          `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIncreaseDepthsV3Api) Reset() {
	*x = PublicIncreaseDepthsV3Api{}
	mi := &file_PublicIncreaseDepthsV3Api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIncreaseDepthsV3Api) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIncreaseDepthsV3Api) ProtoMessage() {}

func (x *PublicIncreaseDepthsV3Api) ProtoReflect() protoreflect.Message {
	mi := &file_PublicIncreaseDepthsV3Api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicIncreaseDepthsV3Api.ProtoReflect.Descriptor instead.
func (*PublicIncreaseDepthsV3Api) Descriptor() ([]byte, []int) {
	return file_PublicIncreaseDepthsV3Api_proto_rawDescGZIP(), []int{0}
}

func (x *PublicIncreaseDepthsV3Api) GetAsks() []*PublicIncreaseDepthV3ApiItem {
	if x != nil {
		return x.Asks
	}
	return nil
}

func (x *PublicIncreaseDepthsV3Api) GetBids() []*PublicIncreaseDepthV3ApiItem {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *PublicIncreaseDepthsV3Api) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublicIncreaseDepthsV3Api) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PublicIncreaseDepthV3ApiItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicIncreaseDepthV3ApiItem) Reset() {
	*x = PublicIncreaseDepthV3ApiItem{}
	mi := &file_PublicIncreaseDepthsV3Api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicIncreaseDepthV3ApiItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicIncreaseDepthV3ApiItem) ProtoMessage() {}

func (x *PublicIncreaseDepthV3ApiItem) ProtoReflect() protoreflect.Message {
	mi := &file_PublicIncreaseDepthsV3Api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicIncreaseDepthV3ApiItem.ProtoReflect.Descriptor instead.
func (*PublicIncreaseDepthV3ApiItem) Descriptor() ([]byte, []int) {
	return file_PublicIncreaseDepthsV3Api_proto_rawDescGZIP(), []int{1}
}

func (x *PublicIncreaseDepthV3ApiItem) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PublicIncreaseDepthV3ApiItem) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

var File_PublicIncreaseDepthsV3Api_proto protoreflect.FileDescriptor

var file_PublicIncreaseDepthsV3Api_proto_rawDesc = string([]byte{
	0x0a, 0x1f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65,
	0x44, 0x65, 0x70, 0x74, 0x68, 0x73, 0x56, 0x33, 0x41, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb9, 0x01, 0x0a, 0x19, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x61, 0x73, 0x65, 0x44, 0x65, 0x70, 0x74, 0x68, 0x73, 0x56, 0x33, 0x41, 0x70, 0x69, 0x12,
	0x31, 0x0a, 0x04, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x44, 0x65,
	0x70, 0x74, 0x68, 0x56, 0x33, 0x41, 0x70, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x61, 0x73,
	0x6b, 0x73, 0x12, 0x31, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73,
	0x65, 0x44, 0x65, 0x70, 0x74, 0x68, 0x56, 0x33, 0x41, 0x70, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x50, 0x0a,
	0x1c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65, 0x44,
	0x65, 0x70, 0x74, 0x68, 0x56, 0x33, 0x41, 0x70, 0x69, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42,
	0x85, 0x01, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x78, 0x63, 0x2e, 0x70, 0x75, 0x73, 0x68,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x42, 0x1e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x61, 0x73, 0x65,
	0x44, 0x65, 0x70, 0x74, 0x68, 0x73, 0x56, 0x33, 0x41, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x48, 0x01, 0x50, 0x01, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x65, 0x78, 0x63, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x2f, 0x6d, 0x65, 0x78,
	0x63, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x2f, 0x77, 0x65, 0x62, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_PublicIncreaseDepthsV3Api_proto_rawDescOnce sync.Once
	file_PublicIncreaseDepthsV3Api_proto_rawDescData []byte
)

func file_PublicIncreaseDepthsV3Api_proto_rawDescGZIP() []byte {
	file_PublicIncreaseDepthsV3Api_proto_rawDescOnce.Do(func() {
		file_PublicIncreaseDepthsV3Api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_PublicIncreaseDepthsV3Api_proto_rawDesc), len(file_PublicIncreaseDepthsV3Api_proto_rawDesc)))
	})
	return file_PublicIncreaseDepthsV3Api_proto_rawDescData
}

var file_PublicIncreaseDepthsV3Api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_PublicIncreaseDepthsV3Api_proto_goTypes = []any{
	(*PublicIncreaseDepthsV3Api)(nil),    // 0: PublicIncreaseDepthsV3Api
	(*PublicIncreaseDepthV3ApiItem)(nil), // 1: PublicIncreaseDepthV3ApiItem
}
var file_PublicIncreaseDepthsV3Api_proto_depIdxs = []int32{
	1, // 0: PublicIncreaseDepthsV3Api.asks:type_name -> PublicIncreaseDepthV3ApiItem
	1, // 1: PublicIncreaseDepthsV3Api.bids:type_name -> PublicIncreaseDepthV3ApiItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_PublicIncreaseDepthsV3Api_proto_init() }
func file_PublicIncreaseDepthsV3Api_proto_init() {
	if File_PublicIncreaseDepthsV3Api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_PublicIncreaseDepthsV3Api_proto_rawDesc), len(file_PublicIncreaseDepthsV3Api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PublicIncreaseDepthsV3Api_proto_goTypes,
		DependencyIndexes: file_PublicIncreaseDepthsV3Api_proto_depIdxs,
		MessageInfos:      file_PublicIncreaseDepthsV3Api_proto_msgTypes,
	}.Build()
	File_PublicIncreaseDepthsV3Api_proto = out.File
	file_PublicIncreaseDepthsV3Api_proto_goTypes = nil
	file_PublicIncreaseDepthsV3Api_proto_depIdxs = nil
}
